#!/usr/bin/env bash

if [ "$1" == "inc" ]; then
  brightnessctl set 5%+
fi

if [ "$1" == "dec" ]; then
  brightnessctl set 5%-
fi

BRIGHTNESS=$(brightnessctl get)
BRIGHTNESS=$((BRIGHTNESS * 100 / 255))
NOTI_ID=$(notify-send.py "Brightness" "$BRIGHTNESS%" \
  --hint string:image-path:video-display boolean:transient:true \
  int:has-percentage:$BRIGHTNESS \
  --replaces-process "brightness-popup")
