#!/usr/bin/env bash

if [ "$1" == "inc" ]; then
  brightnessctl set 5%+
fi

if [ "$1" == "dec" ]; then
  brightnessctl set 5%-
fi

BRIGHTNESS=$(brightnessctl get)
BRIGHTNESS=$((BRIGHTNESS * 100 / 255))

# Send notification with standard notify-send
notify-send "Brightness" "$BRIGHTNESS%" \
  -i video-display \
  -h string:x-canonical-private-synchronous:brightness-popup \
  --hint=int:value:"$BRIGHTNESS" \
  --expire-time=1000
