#!/usr/bin/env bash

function main() {
    VOLUME=$(pamixer --get-volume)
    case $1 in
        "up")
           pamixer -i 2
           ;;
        "down")
           pamixer -d 2
           ;;
        "mute")
           pamixer --toggle-mute
           if [[ $(pamixer --get-volume-human) =~ "muted" ]]; then
               VOLUME=0
           fi
           ;;
    esac

    case $VOLUME in
        [1-9]|1[0-9])
            ICON=audio-volume-low
            ;;
        2[0-9]|3[0-9]|4[0-9]|5[0-9])
            ICON=audio-volume-medium
            ;;
        6[0-9]|7[0-9]|8[0-9]|9[0-9]|100)
            ICON=audio-volume-high
            ;;
        0)
            ICON=audio-volume-muted
            ;;
    esac
    echo $ICON

    NOTI_ID=$(notify-send.py "Volume" "$VOLUME/100" \
                             --hint string:image-path:$ICON boolean:transient:true \
                                    int:has-percentage:$VOLUME \
                             --replaces-process "volume-popup")
}

main $@
