#!/usr/bin/env bash

SYSD_CONFIG="/boot/loader/entries/MiniBeast.conf"

if [ "$EUID" -ne 0 ]; then
    echo -e "\033[1;31mMust be run as root\033[0m"
    exit 1
else
    if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^[0-9]+?\.{1}[0-9]+?\.{1}[0-9]+?-??[0-9a-zA-Z\-]*?$ ]]; then
        echo -e "\033[1;31mNot a valid kernel version\033[0m"
        exit 1
    elif [[ ! -z "$1" ]] && [[ ! -d /usr/src/linux-${1} ]]; then
        echo -e "\033[1;31mKernel not installed\033[0m"
        exit 1
    elif [[ ! -f $SYSD_CONFIG ]] || [[ -z "$1" ]]; then
        echo -e "\033[1;34m:: \033[1;37mUpdating grub\033[0m"
        grub-mkconfig -o /boot/grub/grub.cfg
        echo "systemd-boot: skipped"
        exit 0
    else
        echo -e "\033[1;34m:: \033[1;37mUpdating grub\033[0m"
        grub-mkconfig -o /boot/grub/grub.cfg
        echo -e "\033[1;34m:: \033[1;37mlinux-${1} --> systemd-boot\033[0m"
        sed -i "s/linux-$(uname -r)/linux-${1}/g" $SYSD_CONFIG
#       sed -i "s/\([0-9]*\.[0-9]*\.[0-9]\)/${1}/" $SYSD_CONFIG
        if $(grep -q "$1" /boot/loader/entries/MiniBeast.conf); then
            echo -e "\033[1;32mSuccessful\033[0m"
        else
            echo -e "\033[1;31mFailed\033[0m"
        fi
    fi
fi
