#!/usr/bin/env bash

ACTIVE=($(awk 'NR==1{print $2,$3,$4,$7,$8,$9}' /proc/stat))
IDLE=($(awk 'NR==1{print $5,$6}' /proc/stat))
((TOTAL_ACTIVE = ${ACTIVE[@]/%/+}0))
((TOTAL_IDLE = ${IDLE[@]/%/+}0))
TOTAL=$((TOTAL_ACTIVE + TOTAL_IDLE))
ACTIVE2=($(awk 'NR==1{print $2,$3,$4,$7,$8,$9}' /proc/stat))
IDLE2=($(awk 'NR==1{print $5,$6}' /proc/stat))
((TOTAL_ACTIVE2 = ${ACTIVE2[@]/%/+}0))
((TOTAL_IDLE2 = ${IDLE2[@]/%/+}0))
TOTAL2=$((TOTAL_ACTIVE2 + TOTAL_IDLE2))
TOTAL_DIFF=$((TOTAL2 - TOTAL))
IDLE_DIFF=$((IDLE2 - IDLE))
USAGE=$(awk "BEGIN {print ($TOTAL_DIFF - $IDLE_DIFF)/$TOTAL_DIFF*100}")
echo "${USAGE%%.*}%"
