#!/usr/bin/env bash

COLOR0=$(xrdb -get color0)
COLOR1=$(xrdb -get color1)
COLOR2=$(xrdb -get color2)
COLOR3=$(xrdb -get color3)
COLOR4=$(xrdb -get color4)
COLOR5=$(xrdb -get color5)
COLOR6=$(xrdb -get color6)
COLOR7=$(xrdb -get color7)
COLOR8=$(xrdb -get color8)
COLOR9=$(xrdb -get color9)
COLOR10=$(xrdb -get color10)
COLOR11=$(xrdb -get color11)
COLOR12=$(xrdb -get color12)
COLOR13=$(xrdb -get color13)
COLOR14=$(xrdb -get color14)
COLOR15=$(xrdb -get color15)
FOREGROUND=$(xrdb -get foreground)
BACKGROUND=$(xrdb -get background)
FONT=$(xrdb -get font)
